### PR TITLE
Bump to ubuntu-24.04 and mambaforge-23.11 in ReadTheDocs

### PR DESCRIPTION
**Pull request by weiji14**
Bump ReadTheDocs os version from `ubuntu-20.04` to `ubuntu-24.04`, and mambaforge version from `4.10` to `23.11`.

References:
- https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
- https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python.

### CODE REVIEW

**Comment by weiji14** [comment]
@dcherian, could I also get maintainer access to https://readthedocs.org/projects/cupy-xarray? I'd like to set up builds for tagged versions following https://readthedocs.org/projects/cupy-xarray (instead of the current state of having just the `latest` version built).

After this, I'd like to cut a `cupy-xarray=0.1.4` release (or maybe `0.2.0`?) to fix compatibility with recent xarray versions >=2024.2.0. Have already drafted the release notes at https://github.com/xarray-contrib/cupy-xarray/releases/tag/untagged-2dd5d8af24fda6b6c114.

**Comment by weiji14** [comment]
@jacobtomlinson or @andersy005, can one of you add me to the maintainer list on ReadtheDocs as mentioned above? Would really like to do a new release to fix compatibility with recent xarray versions.

**Comment by dcherian** [comment]
Sorry for the delay, I've sent an invite.

**Comment by weiji14** [comment]
Thanks @dcherian! Have set up versioned builds for cupy-xarray now:

image

**Pull request merged**
