### PR TITLE
Enable API reference docs to show accessor methods

### LINKED ISSUE #5: add API to docs build
autodoc/autosummary import the package to automatically add the docstrings.

This means cupy-xarray and cupy are imported. importing cupy fails on RTD saying it can't find libcuda.

It'd be nice to find a workaround. 

Worst case, I guess we can run autodoc locally and then push the generated html?

(note that installing cuda brings in cudatoolkit which is a 800MB download; it'd be nice to just not do that)

### PR DESCRIPTION
**Pull request by weiji14**
Previously, the API docs section of `cupy-xarray` has been disabled on because `import cupy` doesn't work on Readthedocs CI without CUDA. Luckily, there is now a `cupy-core` package on `conda-forge` (see https://github.com/conda-forge/cupy-feedstock/pull/241) that makes CUDA optional, so we can use that to build the API docs!

**Preview** at https://cupy-xarray--44.org.readthedocs.build/api.html

cupy-xarray API Reference documentation page

(Yeah, not sure why some of those API methods are centre-aligned :sweat_smile:)

I've also updated the 'Contributing documentation' section in the contributing guide which had some typos. Full steps to reproduce the docs build are:

```bash
conda env create --file ci/doc.yml
conda activate cupy-xarray-doc

cd docs
make html
```

References:
- https://github.com/conda-forge/cupy-feedstock/issues/229
- https://sphinx-autosummary-accessors.readthedocs.io/en/stable/usage.html

Fixes #5

### CODE REVIEW

**Comment by keewis** [comment]
> (Yeah, not sure why some of those API methods are centre-aligned 😅)

I think that's because those don't have docstrings (`DataArray.cupy.get()` doesn't, either, but it shares the table with methods that do have one).

**Comment by weiji14** [comment]
> Edit2: I'd also advise against using `numpydoc` and `napoleon` together, they don't always work well together

Ok, removed `numpydoc` at commit 5087d89ba012c8afafade10c5e1601db721ce06f!

> Edit3: to install the package, I'd follow the recommendation documented by [RTD](https://docs.readthedocs.io/en/stable/faq.html#i-need-to-install-a-package-in-a-environment-with-pinned-versions) (add `-e ..` to the pip section in the environment file) – this is also what we're doing in `xarray`

Ah yes, I was trying with one dot `.`, but forgot that two dots `..` are needed to move up a directory! Done at ccc192513bb745465b2da95ea483050e1ba1dc91 (and contributing instruction docs also updated to remove `pip install --editable=.` part).

> Edit: looks like all of them are centered, just that some of them have longer strings

Hmm you're correct, they are all center-aligned. Let me try to play around with the docstrings and/or the sphinx template.

**Comment by weiji14** [comment]
Ok, couldn't figure out how to remove the center-alignment :sweat_smile:, I had a look at other xarray-contrib repos using the Furo theme, and it seems like [xwrf](https://xwrf.readthedocs.io/en/stable/reference/api.html) has the same issue, but [cf-xarray](https://cf-xarray.readthedocs.io/en/latest/api.html) doesn't.

So... I just added in the some docstrings to make it look less empty. Maybe @dcherian or someone else can look at [cf-xarray's css file](https://github.com/xarray-contrib/cf-xarray/blame/v0.9.1/doc/_static/style.css) and figure out how to remove the centre-alignment issue.

**Comment by dcherian** [comment]
Nice work @weiji14 I've added you as maintainer so you should be able to click merge here :)

re: center-aligning. I do not recall doing anything specific. Apparently [flox](https://flox.readthedocs.io/en/latest/api.html) has this issue too, i suspect it is a regression in `furo`

**Comment by weiji14** [comment]
> re: center-aligning. I do not recall doing anything specific. Apparently [flox](https://flox.readthedocs.io/en/latest/api.html) has this issue too, i suspect it is a regression in `furo`

Ah ok, maybe best to report this upstream then at https://github.com/pradyunsg/furo? I'm not sure whether the API docs in `flox` or `cf-xarray` looked like this before, so can't tell if it's a regression bug. It looks as though Furo is centering tables by default, so maybe we need a directive to left align it, but I couldn't find out exactly how.

> Nice work @weiji14 I've added you as maintainer so you should be able to click merge here :)

Thanks! You must have read my mind. Secretly, I've been hoping to get maintainer access after this PR because I have some free time next week, so maybe (just maybe) I'll put in some time to update #10 :smiling_imp:

Will leave this open a bit longer in case anyone has other suggestions, otherwise I'll go ahead and merge this sometime tomorrow.

**Pull request merged**
