### PR TITLE
Let user decide which cupy version to use

### LINKED ISSUE #66: Let users decide which cupy to use
As of right now, there are three `pip install` packages which one can use to install cupy: `cupy` which will build cupy from source and the two prebuild versions `cupy-cuda12x` and `cupy-cuda11x`.
This library only allows for `cupy` to be installed. This clashes with other libraries, e.g. cucim, which only allows installing with prebuild options.
Also, having only the source building `cupy` option available introduces the risk of build-failures on systems which would work fine with the prebuild ones and costs time when installing this library.

Therefore, I would like to present two possible solutions.

First: Remove cupy dependency completely and change the installation instructions that the user must cupy by themselves.

Second: Remove cupy dependency from the dependency list and introduce 3 new optional dependencies:

`pyproject.toml`:

```toml
...
dependencies = [
    "cupy",
    "xarray>=2024.02.0",
]

[project.optional-dependencies]
test = [
    "dask",
    "pytest",
]
source = [
    "cupy"
]
cuda12 = [
    "cupy-cuda12x",
]
cuda11 = [
    "cupy-cuda11x",
]

...
```

That way, a user can install this library with e.g. `pip install cupy-xarray[cuda12]`

I would welcome any feedback and other ideas on this. If you make a decision about this, I would be happy to implement it and open a pull request.

### PR DESCRIPTION
**Pull request by relativityhd**
Implement solution for #66 as discussed.

Remove cupy from dependencies and add three extras where each requires a different cupy version: cupy (building from source), and the two prebuild cupy-cuda12x and cupy-cuda11x

Closes #66

### CODE REVIEW

**Review by jacobtomlinson — COMMENTED** [review]
I felt like the general concensus on #66 was to remove the dependency altogether and add an import time check no?

**Comment by relativityhd** [comment]
@jacobtomlinson This would indeed remove the dependency and add an import time check. _Additionally_, this would add the possibility for the user to install cupy with a pip-extra.

**Review by dcherian — APPROVED** [review]

**Review by jacobtomlinson — APPROVED** [review]
This looks good to me!

**Review by weiji14 — APPROVED** [review]
Thanks @relativityhd! I might not get to a release this week, but will try to find time next month to do so.

**Pull request merged**
